services:
  - type: web
    name: verdaccio
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    env: docker
    disk:
      name: verdaccio-data
      mountPath: /verdaccio/storage
      sizeGB: 1 # optional
