services:
  - type: web
    name: mysite
    repo: https://github.com/TerribleDev/verdaccio/blob/master # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: 5.x # optional (uses repo default)
    disk:
      name: verdaccio-data
      mountPath: /verdaccio/storage
      sizeGB: 1 # optional